define([], function () {
    return {
        "PropertyPaneDescription": "Displays a list as a highly responsive filterable table, along with an optional lookup table.",
        "Table1GroupName": "Primary Table",
        "Table1TitleFieldLabel": "Table Title",
        "Table1SiteNameFieldLabel": "Site Name",
        "Table1ListNameFieldLabel": "List Name",
        "Table1VisibleColsMobileFieldLabel": "Visible Columns (Mobile)",
        "Table1VisibleColsTabletFieldLabel": "Visible Columns (Tablet)",
        "Table1VisibleColsDesktopFieldLabel": "Visible Columns (Desktop)",
        "LookupColumnFieldLabel": "Lookup Column",
        "Table2GroupName": "Secondary Table",
        "Table2TitleFieldLabel": "Table Title",
        "Table2SiteNameFieldLabel": "Site Name",
        "Table2ListNameFieldLabel": "List Name",
        "ShowTable2FieldLabel": "Show Secondary Table",
        "Table2AddPropsGroupName": "Secondary Table Properties",
        "Table2VisibleColsMobileFieldLabel": "Visible Columns (Mobile)",
        "Table2VisibleColsTabletFieldLabel": "Visible Columns (Tablet)",
        "Table2VisibleColsDesktopFieldLabel": "Visible Columns (Desktop)",
        "Table2OrderByColumn1FieldLabel": "Group By",
        "Table2OrderByColumn2FieldLabel": "Order By",
        "Table2OrderByColumn3FieldLabel": "Order By Parent",
    }
});